import Head from "next/head";
import styles from "@/styles/Home.module.css";
import WebsiteHeader from "@/components/WebsiteHeader";
import Footer from "@/components/Footer";
import ContactMe from "@/components/ContactMe";
import Profile from "@/components/Profile";
import Skills from "@/components/Skills";

export default function Home() {
  return (
    <div className={styles.body}>
      <Head>
        <meta charSet="UTF-8" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Jakob Faarbæk Gregersen</title>
      </Head>
      <div className={styles.body}>
        <WebsiteHeader />
        <div className={styles.middleContainer}>
          <Profile />
          <hr className={styles.hr} />
          <Skills />
          <hr className={styles.hr} />
          <ContactMe />
        </div>
      </div>
      <Footer />
    </div>
  );
}
