import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <link rel="stylesheet" href="../styles/styles.css" />
        <link rel="icon" href="../../public/favicon.ico" />{" "}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&family=Oxygen&family=Play&family=Space+Grotesk&display=swap"
          rel="stylesheet"
        />
        <title>Jakob Faarbæk Gregersen</title>
      </Head>
      <div className={styles.body}>
        <div className={styles.topContainer} style={{ zIndex: 0 }}>
          <h1>Jakob F. G.</h1>
          <h2>Software Developer &amp; Fisherman</h2>
          <Image
            src="/wave.png"
            alt="Handdrawn wave"
            width={150}
            height={48}
            className={styles.wave}
            style={{ bottom: "200px", left: "100px" }}
          />
          <Image
            src="/wave.png"
            alt="Handdrawn wave"
            width={150}
            height={48}
            className={styles.wave}
            style={{ bottom: "100px", left: "300px" }}
          />
          <Image
            src="/wave.png"
            alt="Handdrawn wave"
            width={150}
            height={48}
            className={styles.wave}
            style={{ bottom: "300px", left: "200px" }}
          />
          <Image
            src="/wave.png"
            alt="Handdrawn wave"
            width={150}
            height={48}
            className={styles.wave}
            style={{ bottom: "140px", right: "200px" }}
          />
          <Image
            src="/wave.png"
            alt="Handdrawn wave"
            width={150}
            height={48}
            className={styles.wave}
            style={{ bottom: "300px", right: "160px" }}
          />
          <div
            style={{
              margin: "0 auto;",
              position: "relative",
              height: "300px;",
              width: "300px",
            }}
          >
            <Image
              src="/fishing.png"
              alt="boy fishing-img"
              width={128}
              height={128}
              className={styles.fishingImg}
              style={{ left: "208px;", top: "4px" }}
            />
            <Image
              src="/keyboard.png"
              alt="keyboard-img"
              width={200}
              height={200}
              className={styles.keyboard}
              style={{ left: "50px" }}
            />
          </div>
        </div>
        <div className="middle-container">
          <div className="profile">
            <Image
              src="/jakob_circle.png"
              alt="portrait-img"
              width={200}
              height={200}
              className={styles.profileImg}
              style={{ left: "50px" }}
            />
            <h2>Welcome to my page</h2>
            <p>
              I am a
              <a
                className={styles.links}
                href="https://www.aau.dk/uddannelser/bachelor/software"
              >
                BSc. of Software Engineering
              </a>
              .
            </p>
            <p>
              I am currently studying a
              <a
                className={styles.links}
                href="https://www.aau.dk/uddannelser/kandidat/software"
              >
                MSc. in Engineering (Software) at Aalborg University (AAU)
              </a>
            </p>
          </div>
          <hr />
          <div className="skills">
            <h2>My Skills</h2>
            <div className="skill-row">
              <Image
                className={styles.programmingImg}
                src="/programming_circle.png"
                alt="Programming-img"
                width={10}
                height={10}
              />
              <h3>Programming</h3>
              <p>
                I enjoy programming as it always provides well defined questions
                with verifiable solutions.
              </p>
              <p>
                To me, the most alluring feature of programming is the great
                "AHA!" moments of solving a problem
              </p>
            </div>
            <div className="skill-row">
              <Image
                className={styles.fishingImg}
                src="/fisker_circle.png"
                alt="Fishing at dawn-img"
                width={10}
                height={10}
              />
              <h3>Fishing</h3>
              <p>
                I enjoy the tranquility of fishing by the lake, watching the
                float waddle in the waves and breathing in nature
              </p>
              <p>
                On the rare occasion that I happen to reel in a fish, I consider
                myself lucky and feel a great sense of accomplishment!
              </p>
            </div>
          </div>
          <hr />
          <div className="contact-me">
            <h3 style={{ marginBottom: "0px" }}>Get In Touch</h3>
            <h3 style={{ marginTop: "0px;", fontSize: "medium" }}>
              If you have a cool fishing trick or a recommendation
            </h3>
            <p>
              Click a contact-button below, to set up a talk with me, so that we
              can fish or code together!
            </p>
            <svg
              aria-hidden="true"
              style={{
                height: "15px;",
                paddingRight: "5px;",
                color: "#708090",
              }}
              focusable="false"
              data-icon="envelope-square"
              role="img"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 448 512"
              data-fa-i2svg=""
            >
              <path
                fill="currentColor"
                d="M400 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h352c26.51 0 48-21.49 48-48V80c0-26.51-21.49-48-48-48zM178.117 262.104C87.429 196.287 88.353 196.121 64 177.167V152c0-13.255 10.745-24 24-24h272c13.255 0 24 10.745 24 24v25.167c-24.371 18.969-23.434 19.124-114.117 84.938-10.5 7.655-31.392 26.12-45.883 25.894-14.503.218-35.367-18.227-45.883-25.895zM384 217.775V360c0 13.255-10.745 24-24 24H88c-13.255 0-24-10.745-24-24V217.775c13.958 10.794 33.329 25.236 95.303 70.214 14.162 10.341 37.975 32.145 64.694 32.01 26.887.134 51.037-22.041 64.72-32.025 61.958-44.965 81.325-59.406 95.283-70.199z"
              ></path>
            </svg>
            <a href="mailto:lilleper.jfg@gmail.com" className={styles.links}>
              Email
            </a>
          </div>
          <div
            style={{ position: "relative", width: "240px;", margin: "0 auto" }}
          >
            <div style={{ position: "absolute", left: "5%" }}>
              <svg
                style={{ height: "15px;", color: "#708090" }}
                aria-hidden="true"
                focusable="false"
                data-icon="linkedin"
                role="img"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 448 512"
              >
                <path
                  fill="currentColor"
                  d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"
                ></path>
              </svg>
              <a
                className={styles.links}
                href="https://www.linkedin.com/in/jakob-faarbæk-gregersen/"
              >
                LinkedIn
              </a>
            </div>
            <img
              src="https://media.giphy.com/media/QXuc5klZIp8pW/giphy.gif?cid=ecf05e47mi7tv2z1590dmzyjxymz9w1am2omsp62mqmb62ck&rid=giphy.gif&ct=s"
              alt="fish-gif"
              style={{ height: "20px;", paddingLeft: "10px" }}
            />
            <div style={{ position: "absolute", right: "5%;", top: "0px" }}>
              <a
                className={styles.links}
                href="https://www.github.com/jakobfaargreg/"
              >
                Github
              </a>
              <svg
                style={{ height: "15px;", color: "#708090" }}
                aria-hidden="true"
                focusable="false"
                data-icon="github"
                role="img"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 496 512"
              >
                <path
                  fill="currentColor"
                  d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"
                ></path>
              </svg>
            </div>
          </div>
        </div>
        <div className="bottom-container">
          <p
            className="subtle"
            style={{
              marginTop: "0px;",
              paddingTop: "20px;",
              fontSize: "small",
            }}
          >
            © 2022 Jakob Faarbæk Gregersen
          </p>
          <div className="subtle" style={{ paddingBottom: "10px" }}>
            <a
              className="links subtle"
              href="https://www.flaticon.com/free-icons/fishing"
              title="fishing icons"
            >
              Fishing
            </a>
            and
            <a
              className="links subtle"
              href="https://www.flaticon.com/free-icons/keyboard"
              title="keyboard icons"
            >
              Keyboard icons created by Freepik - Flaticon
            </a>
          </div>
        </div>
      </div>
    </>
  );
}
